sonar.projectKey=iris-website-key
sonar.projectName=iris-website
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/coverage/**,**/prisma/**,**/public/**,**/*.config.*,**/next-env.d.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
